application: goryofolio
version: 2
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

handlers:

#- url: /
#  script: goryofolio.app

- url: /update_schema
  script: update_schema_handler.app  # path to webapp2 application definition.
  login: admin
  secure: always

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /testpaginggyo
  script: testpaginggyo.app

- url: /messageme
  script: messageme.app

- url: /.*
  script: goryofolio.app

libraries:                                                                      
- name: jinja2                                                                  
  version: latest                                                               
- name: markupsafe                                                              
  version: latest     
