application: goryofolio
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /
  script: goryofolio.app

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /testgyo
  script: testgyo.app

# - url: /.*
#  script: not_found.app

libraries:                                                                      
- name: jinja2                                                                  
  version: latest                                                               
- name: markupsafe                                                              
  version: latest     
